version: '3.8'

services:
  postgres:
    image: postgres:17.6
    container_name: doc_workflow_db
    environment:
      POSTGRES_DB: doc_workflow
      POSTGRES_USER: docWf
      POSTGRES_PASSWORD: docWf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docWf -d doc_workflow"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: doc_workflow_data
