spring:
  application:
    name: document-workflow
  profiles:
    default: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/doc_workflow
    username: docWf
    password: docWf

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    default-schema: public
    liquibase-schema: public
    change-log: classpath:/db/migration/database-doc.workflow-changelog-master.xml
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false

app:
  batch:
    size: 10
    submit:
      fixed-delay: 100000
    approve:
      fixed-delay: 100000

api:
  base-url: http://localhost:8080/api/v1/document

logging:
  level:
    ru.kolivim.document.workflowl: DEBUG
    org:
      springframework: DEBUG
  file:
    name: logs/log