spring:
  application:
    name: document-workflow
  profiles:
    default: dev
  datasource:
#    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doc_workflow
    username: docWf
    password: docWf
#    hikari:
#      connection-init-sql: CREATE SCHEMA IF NOT EXISTS doc_workflow

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
#    show-sql:false

  liquibase:
    default-schema: public
    liquibase-schema: public
#    default-schema: doc_workflow
    change-log: classpath:/db/migration/database-doc.workflow-changelog-master.xml
    enabled: true



app:
  batch:
    size: 10
    submit:
      fixed-delay: 100000
    approve:
      fixed-delay: 100000

api:
  base-url: http://localhost:8080/api/v1/document

logging:
  level:
    ru.kolivim.document.workflowl: DEBUG
    org:
      springframework: DEBUG
  file:
    name: logs/log